-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 22:13:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IOT4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IOT4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IOT4` DEFAULT CHARACTER SET utf8 ;
USE `IOT4` ;

-- -----------------------------------------------------
-- Table `IOT4`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IOT4`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOT4`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IOT4`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `session_id` INT NOT NULL,
  `session_user_id` INT NOT NULL,
  `time_stamp` DATETIME NULL,
  `roll` DECIMAL(6,6) NULL,
  `pitch` DECIMAL(6,6) NULL,
  `yaw` DECIMAL(6,6) NULL,
  `longitude` DECIMAL(6,6) NOT NULL,
  `latitude` DECIMAL(6,6) NULL,
  `x` DECIMAL(6,6) NULL,
  `y` DECIMAL(6,6) NULL,
  `z` DECIMAL(6,6) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `session_id`, `session_user_id`, `longitude`),
  INDEX `fk_data_session1_idx` (`session_id` ASC, `session_user_id` ASC),
  CONSTRAINT `fk_data_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `IOT4`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
